substitutions:
  esp_name: anemometer
  esp_friendlyname: Anemometer
  esp_id: anemometer
  esp_otamode_check_interval: 5s
  esp_boot_connect_delay: 100ms
  esp_boot_connect_timeout: 30s
  esp_uptime_pub_delay: 200ms
  esp_day_sleep_min_duration_s: 120     # 2min
  esp_day_sleep_short_duration_s: 300.  # 5min
  esp_day_sleep_medium_duration_s: 900  # 15min
  esp_day_sleep_long_duration_s: 3600   # 1h
  esp_night_sleep_duration_s: 1800      # 30min
  esp_battery_percent_max: 90
  esp_battery_percent_high: 75
  esp_battery_percent_low: 30
  esp_speed_history_timeout_s: 960     # 16min
  esp_direction_history_timeout_s: 660 # 11min

esphome:
  name: ${esp_name}
  friendly_name: ${esp_friendlyname}
  comment: Wind speed measurement (D1MiniPro/TP4056/Li16650/US1881)
  on_boot:
    priority: 900
    then:
      - script.execute: start

esp8266:
  board: d1_mini_pro
  restore_from_flash: True  

# Enable logging
logger:
  baud_rate: 0 # disable to reduce power draw
  level: NONE

# Enable Home Assistant API
api:
  reboot_timeout: 0s # empeche un reboot auto si deconnection breve
  encryption:
    key: !secret anemometer_api_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
      hidden: true # to prevent from scanning if connection fails
      bssid: !secret wifi_bssid #todo
      channel: !secret wifi_channel #todo
  fast_connect: True # scan disabled to reduce power draw
  post_connect_roaming: false
  power_save_mode: NONE
  min_auth_mode: WPA2
  manual_ip: # static to reduce power draw
    static_ip: X.Y.Z.T
    gateway: X.Y.1.1
    subnet: 255.255.255.0
    dns1: X.Y.1.1
  ap:
    ap_timeout: 0s # disabled to reduce power draw

#status_led: # disabled to reduce power draw
#  pin: GPIO2

sun:                        
  id: ${esp_id}_sun         
  latitude: !secret home_latitude
  longitude: !secret home_longitude

time:
  - platform: homeassistant
    id: ${esp_id}_time
    on_time_sync:
      then:
        # Update last restart time, but only once.
        - if:
            condition:
              lambda: 'return id(${esp_id}_last_restart).state == "";'
            then:
              - text_sensor.template.publish:
                  id: ${esp_id}_last_restart
                  state: !lambda 'return id(${esp_id}_time).now().strftime("%a %d %b %Y - %I:%M:%S %p");'

globals:
  - id: ${esp_id}_half_turn_pulses
    type: int
    restore_value: false
    initial_value: '0'
  - id: ${esp_id}_speed_time_history
    type: time_t[5]
    restore_value: true
    initial_value: '{0, 0, 0, 0, 0}'
  - id: ${esp_id}_speed_data_history
    type: float[5]
    restore_value: true
    initial_value: '{0.0, 0.0, 0.0, 0.0, 0.0}'
  - id: ${esp_id}_speed_history_index
    type: int
    restore_value: true
    initial_value: '0'
  - id: ${esp_id}_direction_time_history
    type: time_t[5]
    restore_value: true
    initial_value: '{0, 0, 0, 0, 0}'
  - id: ${esp_id}_direction_data_history
    type: int[5]
    restore_value: true
    initial_value: '{0, 0, 0, 0, 0}'
  - id: ${esp_id}_direction_history_index
    type: int
    restore_value: true
    initial_value: '0'

output:
  - platform: gpio
    id: ${esp_id}_power_sensors
    pin: D5

binary_sensor:
  - platform: homeassistant
    internal: True
    id: ${esp_id}_ota_mode
    entity_id: input_boolean.esphome_ota_mode
  - platform: status # for device wakeups history monitoring
    name: "Status"
  - platform: gpio
    internal: True
    id: ${esp_id}_speed_pulse_counter
    pin:
      number: GPIO12
      mode: INPUT_PULLUP
    filters:
      - delayed_on_off: 10ms
    on_press:
      - then:
          - lambda: |-
              id(${esp_id}_half_turn_pulses) += 1;
  - platform: gpio
    internal: True
    id: ${esp_id}_phase_a
    pin:
      number: GPIO4
      mode: INPUT
  - platform: gpio
    internal: True
    id: ${esp_id}_phase_b
    pin:
      number: GPIO5
      mode: INPUT
deep_sleep:
  id: ${esp_id}_deep_sleep

text_sensor:
  - platform: template
    name: 'Last Restart'
    id: ${esp_id}_last_restart
    icon: mdi:clock
    entity_category: diagnostic    
  - platform: template
    id: ${esp_id}_wind_direction
    icon: mdi:navigation
    name: "Wind direction"
    update_interval: never
    lambda: |-
      if (id(${esp_id}_phase_a).state) {
        if (id(${esp_id}_phase_b).state) {
          return "north";
        } else {
          return "east";
        }
      } else {
        if (id(${esp_id}_phase_b).state) {
          return "south";
        } else {
          return "west";
        }
      }
  - platform: template
    id: ${esp_id}_average_wind_direction
    icon: mdi:navigation    
    name: "Smoothed wind direction"
    update_interval: never
    lambda: |-
        auto& history_index = id(${esp_id}_direction_history_index);
        auto& history_data = id(${esp_id}_direction_data_history);
        auto& history_time = id(${esp_id}_direction_time_history);
        time_t now = id(${esp_id}_time).now().timestamp;

        // Wind direction
        enum class WindDirection : int { North = 1, East, South, West };
        auto wind_direction = id(${esp_id}_wind_direction).state;

        
        WindDirection current_wind_direction = WindDirection::North;
        if (wind_direction == "east") {
          current_wind_direction = WindDirection::East;
        } else if (wind_direction == "south") {
          current_wind_direction = WindDirection::South;
        } else if (wind_direction == "west") {
          current_wind_direction = WindDirection::West;
        }

        // History
        if (history_index == 0) {
          history_time[0] = now;
          history_data[0] = (int)current_wind_direction;
          history_time[1] = 0;
          history_data[1] = 0;
          history_time[2] = 0;
          history_data[2] = 0;
          history_time[3] = 0;
          history_data[3] = 0;
          history_time[4] = 0;
          history_data[4] = 0;
          history_index = 1;
        } else if (history_index == 5) {
          history_time[0] = now;
          history_data[0] = (int)current_wind_direction;
          history_index = 1;
        } else {
          history_time[history_index] = now;
          history_data[history_index] = (int)current_wind_direction;
          history_index += 1;
        }
        int count[6] = {0, 0, 0, 0, 0, 0};
        for (uint32_t idx = 0; idx < 5; idx++) {
          if (history_time[idx] != 0 && now >= history_time[idx]) {
            if ((now - history_time[idx]) <= ${esp_direction_history_timeout_s}) {
              count[ history_data[idx] ] += 1;
            }
          }
        }
        WindDirection dir_max = WindDirection::North;
        int max = count[(int)dir_max];
        for (auto dir : {WindDirection::East, WindDirection::South, WindDirection::West}) {
          if (count[(int)dir] > max) {
            max = count[(int)dir];
            dir_max = dir;
          }
        }
        if (dir_max == WindDirection::East) {
          return "east";
        } else if (dir_max == WindDirection::South) {
          return "south";
        } else if (dir_max == WindDirection::West) {
          return "west";
        } else {
          return "north";
        }

sensor:
  - platform: template
    id: ${esp_id}_uptime
    name: "Uptime"
    unit_of_measurement: "s"
    update_interval: never
    accuracy_decimals: 1
    icon: mdi:clock-start
    entity_category: diagnostic
    lambda: |-
      return millis() / 1000.0;
  - platform: wifi_signal
    name: "Wifi Signal"
    id: ${esp_id}_wifi_signal_db
    update_interval: never
    unit_of_measurement: dB
    accuracy_decimals: 0
    icon: mdi:wifi
    entity_category: diagnostic
  - platform: adc
    name: "Battery Voltage"
    id: ${esp_id}_batvolt
    pin: A0
    accuracy_decimals: 2
    update_interval: never
    unit_of_measurement: "V"
    device_class: voltage
    filters:
      - multiply: 4.4 # voltage divider = (120k+220k+100k)/100k
  - platform: template
    name: "Battery %"
    id: ${esp_id}_batpercent
    lambda: |-
      id(${esp_id}_batvolt).update();
      return id(${esp_id}_batvolt).state;
    accuracy_decimals: 0
    update_interval: never
    unit_of_measurement: "%"
    device_class: battery
    filters:
      - calibrate_linear:
          method: exact
          datapoints:
            - 0.00 -> 0.0
            - 3.20 -> 1.0
            - 3.39 -> 10.0
            - 3.75 -> 50.0
            - 4.11 -> 90.0
            - 4.20 -> 100.0
      - lambda: |-
          if (x < 0) {
            return 0;
          } else if (x > 100) {
            return 100;
          } else {
            return x;
          }
  - platform: template
    id: ${esp_id}_wind_speed
    name: "Wind speed"
    unit_of_measurement: "km/h"
    device_class: wind_speed
    icon: "mdi:speedometer"
    accuracy_decimals: 1
    update_interval: never
    filters:
      - calibrate_linear:
          method: exact
          datapoints:
            - 0.0 -> 0.0
            - 20.0 -> 12.0
            - 50.0 -> 25.0 
            - 80.0 -> 40.0
            - 100.0 -> 50.0
            - 120.0 -> 60.0
    lambda: |-
        return id(${esp_id}_rpm).state;
  - platform: template
    id: ${esp_id}_rpm
    name: "RPM"
    unit_of_measurement: "tr/min"
    device_class: wind_speed
    icon: "mdi:speedometer"
    accuracy_decimals: 0
    update_interval: never
    lambda: |-
        return id(${esp_id}_half_turn_pulses) * 5.0;
  - platform: template
    id: ${esp_id}_average_wind_speed
    name: "Average wind speed"
    unit_of_measurement: "km/h"
    device_class: wind_speed
    icon: "mdi:speedometer"
    accuracy_decimals: 1
    update_interval: never
    lambda: |-
        auto& history_index = id(${esp_id}_speed_history_index);
        auto& history_data = id(${esp_id}_speed_data_history);
        auto& history_time = id(${esp_id}_speed_time_history);
        time_t now = id(${esp_id}_time).now().timestamp;

        // Wind speed
        float current_wind_speed = id(${esp_id}_wind_speed).state;

        // History
        if (history_index == 0) {
          history_time[0] = now;
          history_data[0] = current_wind_speed;
          history_time[1] = 0;
          history_data[1] = 0.0;
          history_time[2] = 0;
          history_data[2] = 0.0;
          history_time[3] = 0;
          history_data[3] = 0.0;
          history_time[4] = 0;
          history_data[4] = 0.0;
          history_index = 1;
        } else if (history_index == 5) {
          history_time[0] = now;
          history_data[0] = current_wind_speed;
          history_index = 1;
        } else {
          history_time[history_index] = now;
          history_data[history_index] = current_wind_speed;
          history_index += 1;
        }
        float sum = 0.0;
        float nb_val = 0.0;
        for (uint32_t idx = 0; idx < 5; idx++) {
          if (history_time[idx] != 0 && now >= history_time[idx]) {
            if ((now - history_time[idx]) <= ${esp_speed_history_timeout_s}) {
              sum += history_data[idx];
              nb_val += 1.0;
            }
          }
        }
        return sum / nb_val;
        
script:
  - id: start
    mode: queued
    then:
      - output.turn_off: ${esp_id}_power_sensors
      - wait_until:
          condition:
            and:
              - wifi.connected:
              - api.connected:
                  state_subscription_only: true
              #- time.has_time: # synchro temps en parallele des trts, sinon deep sleep de 1h
          timeout: ${esp_boot_connect_timeout}
      - delay: ${esp_boot_connect_delay}
      - if:
          condition:
            and:
              - wifi.connected:
              - api.connected:
                  state_subscription_only: true
              #- time.has_time: # synchro temps en parallele des trts, sinon deep sleep de 1h
          then:
            - script.execute: mainloop
          else:
            - logger.log: 
                format: 'Connection timeout, will try again after deep sleep'
                level: WARN
            - script.execute: measure_battery_level
            - script.wait: measure_battery_level
            - script.execute: enter_sleep

  - id: mainloop
    mode: queued
    then:
      - if:
          condition:
            binary_sensor.is_on: ${esp_id}_ota_mode
          then:
            - delay : ${esp_otamode_check_interval}
            - logger.log:
                format: 'Skipping deep sleep, per esphome_ota_mode'
                level: WARN
            - script.execute: mainloop
          else:
            - output.turn_on: ${esp_id}_power_sensors
            - script.execute: read_sensors
            - script.execute: measure_wifi_signal
            - script.execute: measure_battery_level
            - script.wait: measure_battery_level
            - script.wait: measure_wifi_signal
            - script.wait: read_sensors
            - output.turn_off: ${esp_id}_power_sensors
            - script.execute: enter_sleep

  - id: enter_sleep
    then:
      #- logger.log: # disabled to reduce power draw
      #   format: "--- ZZZZZzzzzz ---"
      #   level: DEBUG
      - component.update: ${esp_id}_uptime
      - delay: ${esp_uptime_pub_delay} # pour avoir le temps de publier la valeur avant le depp sleep
      - deep_sleep.enter:
          id: ${esp_id}_deep_sleep 
          sleep_duration: !lambda |-
            auto sun = id(${esp_id}_sun);
            auto battery = id(${esp_id}_batpercent);
            if (sun == nullptr || sun->is_above_horizon() == false) {
              return ${esp_night_sleep_duration_s} * 1000;
            } else if (battery == nullptr || isnan( battery->state )) {
              return ${esp_night_sleep_duration_s} * 1000;
            } else if (battery->state < ${esp_battery_percent_low}) {
              return ${esp_day_sleep_long_duration_s} * 1000;
            } else if (battery->state < ${esp_battery_percent_high}) {
              return ${esp_day_sleep_medium_duration_s} * 1000;
            } else if (battery->state < ${esp_battery_percent_max}) {
              return ${esp_day_sleep_short_duration_s} * 1000;
            } else {
              return ${esp_day_sleep_min_duration_s} * 1000;
            }

  - id: read_sensors
    then:
      - lambda: |
          id(${esp_id}_half_turn_pulses) = 0;
      - delay: 6s
      - component.update: ${esp_id}_rpm
      - component.update: ${esp_id}_wind_speed
      - component.update: ${esp_id}_wind_direction
      - component.update: ${esp_id}_average_wind_speed
      - component.update: ${esp_id}_average_wind_direction

  - id: measure_wifi_signal
    then:
      - component.update: ${esp_id}_wifi_signal_db
  
  - id: measure_battery_level
    then:
      - component.update: ${esp_id}_batpercent


